In [2]:
import numpy as np

In [8]:
# array   np.array
# Massivdə yalnız BİR növ məlumat ola bilər 
# Siz ona həm rəqəm, həm də yazı verəndə, NumPy "panikaya düşmür". O, bütün elementləri əhatə edə biləcək ən ümumi tipi seçir.
# Buna texniki dildə Upcasting deyilir

a = np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [14]:
np.array([[1,2,3],[3,4,5]])

array([[1, 2, 3],
       [3, 4, 5]])

In [18]:
b = np.array([1,2,3,"jet academy"])
print(b)
print(type(b[1]))

['1' '2' '3' 'jet academy']
<class 'numpy.str_'>


In [24]:
# biz demişdik ki, array daxilində 1 type da data saxlayır. Yuxarıda olan koda diqqət etseniz görərsiniz ki, həm int həm də str dəyər var. 
# ama son olaraq nəticədə numpy array onların hamısını bir data type çevrir
# bu zaman sual yaranır? ne zaman hamısını str ne zaman int ne zaman float və.s edir?
# burada artıq vahid qəbul edilmiş bir sıralama var 

"""
NumPy tipləri qarışdıranda bu ardıcıllıqla "yuxarı" (upcast) qalxır:

Bool (True/False) - Ən zəif

Int (Tam ədəd)

Float (Kəsr ədəd)

String (Yazı) - Ən güclü
"""

a  = np.array([1,2,3,4,5])
print(a,end="\n\n")

b = np.array([1,2,3,4.5])
print(b,end="\n\n")

c = np.array([True,1,2,3])
print(c)


[1 2 3 4 5]

[1.  2.  3.  4.5]

[1 1 2 3]


In [25]:
# np.arange 

# 0-dan 10-a qədər (10 daxil deyil)
a = np.arange(10)
print(a) 
# Nəticə: [0 1 2 3 4 5 6 7 8 9]

[0 1 2 3 4 5 6 7 8 9]


In [26]:
# 5-dən 10-a qədər
b = np.arange(5, 10)
print(b)
# Nəticə: [5 6 7 8 9]

[5 6 7 8 9]


In [27]:
# 0-dan 20-yə qədər, 5-5 artır
c = np.arange(0, 21, 5) 
print(c)
# Nəticə: [ 0  5 10 15 20]

[ 0  5 10 15 20]


In [28]:
# Python-un adi range() funksiyası kəsr ədədlərlə ("0.5 addımla get") işləyə bilmir. np.arange isə bacarır.

# 0-dan 1-ə qədər, 0.1 addımla
d = np.arange(0, 1, 0.1)
print(d)
# Nəticə: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [29]:
# step mənfi də ola bilər! Bu zaman sayma əksinə gedir. Amma diqqətli olun: start > stop olmalıdır. 

# 10-dan 0-a doğru geri sayım
geri = np.arange(10, 0, -1)
print(geri)
# Nəticə: [10  9  8  7  6  5  4  3  2  1]

[10  9  8  7  6  5  4  3  2  1]


In [32]:
# Çevrilmələr və Məntiq Fərqləri 
# Məlumatlar bizə həmişə hazır NumPy formatında gəlmir. Bəzən verilənlər bazasından tuple (dəyişməz siyahı) və ya JSON-dan list kimi gəlir.
# Vacib Qeyd: Tuple Python-da dəyişməzdir (immutable), amma onu np.arrayə çevirəndə yaranan massiv dəyişə bilən (mutable) olur. Yəni arr_tuple[0] = 100 yaza bilərsiniz.

# 1. Python List (Dəyişə bilən)
qiymetler_list = [50, 60, 75, 90]

# 2. Python Tuple (Dəyişməyən)
koordinatlar_tuple = (10, 20, 30, 40)

# ÇEVRİLMƏ: np.array() sehrli qapıdır
arr_list = np.array(qiymetler_list)
arr_tuple = np.array(koordinatlar_tuple)

print("Listdən gələn:", arr_list)   # [50 60 75 90]
print("Tuple-dan gələn:", arr_tuple) # [10 20 30 40]


Listdən gələn: [50 60 75 90]
Tuple-dan gələn: [10 20 30 40]


In [33]:
koordinatlar_tuple = (10, 20, 30, 40)
arr_tuple = np.array(koordinatlar_tuple)
arr_tuple[0] = 100
print("Tuple-dan gələn:", arr_tuple) # [10 20 30 40]


Tuple-dan gələn: [100  20  30  40]


In [35]:
qiymetler = [50, 60, 75, 85, 90]

# Düsturu əllə yazırıq
ortalama_list = sum(qiymetler) / len(qiymetler)

print(f"List ilə ortalama: {ortalama_list}",end="\n\n")

np_qiymetler = np.array([50, 60, 75, 85, 90])

# Sadəcə .mean() çağırırıq
ortalama_np = np.mean(np_qiymetler)
# Və ya: np_qiymetler.mean()

print(f"NumPy ilə ortalama: {ortalama_np}")


List ilə ortalama: 72.0

NumPy ilə ortalama: 72.0


In [37]:
# Əlimizdə bir neçə məhsulun manatla qiyməti var: (34, 85, 170). Biz bunları dollara çevirməliyik (Hər birini 1.7-yə bölməliyik).

qiymetler_tup = (34, 85, 170)

# print(qiymetler_tup / 1.7) 
# XƏTA! TypeError: Tuple tipini float tipinə bölmək olmaz.

In [38]:
qiymetler_tup = (34, 85, 170)

# 1. Müvəqqəti list
yeni_qiymetler = []

# 2. Dövr (Hər birini tək-tək hesablayırıq)
for qiymet in qiymetler_tup:
    hesab = qiymet / 1.7
    yeni_qiymetler.append(hesab)

# 3. Yenidən Tuple-a çevirmək
netice_tup = tuple(yeni_qiymetler)

print("Tuple nəticəsi:", netice_tup)
# Nəticə: (20.0, 50.0, 100.0)

Tuple nəticəsi: (20.0, 50.0, 100.0)


In [40]:

# Tuple-ı birbaşa Array-ə çevirib qəbul edirik
qiymetler_arr = np.array((qiymetler_tup))

# BÜTÜN İŞ BU SƏTİRDƏ HƏLL OLUNUR:
netice_arr = qiymetler_arr / 1.7

print("NumPy nəticəsi:", netice_arr)
# Nəticə: [ 20.  50. 100.]

NumPy nəticəsi: [ 20.  50. 100.]


In [42]:
# mean  ve median 

# Ev qiymətləri (min manatla)
ev_qiymetleri = np.array([50, 60, 55, 65, 500]) # 500 - "Outlier" (kənarlaşma)

orta = np.mean(ev_qiymetleri)
median = np.median(ev_qiymetleri)

print(f"Orta qiymət: {orta}")   # Nəticə: 146.0 (Reallığı əks etdirmir)
print(f"Median qiymət: {median}") # Nəticə: 60.0 (Daha realdır)

Orta qiymət: 146.0
Median qiymət: 60.0


In [43]:
# percentile
# Saytın açılma vaxtları (millisaniyə ilə)
request_times = np.array([100, 102, 98, 105, 110, 5000]) # 5000 - server donub

# 95-ci percentili tapaq
p95 = np.percentile(request_times, 95)

print(f"İstifadəçilərin 95%-i üçün sayt {p95} ms-dən tez açılır.")
# Bu, "Outlier"ləri nəzərə alaraq performans hədəfi qoymağa kömək edir.

İstifadəçilərin 95%-i üçün sayt 3777.5 ms-dən tez açılır.


In [44]:

# 10 tələbənin imtahan balları (0-100 arası)
ballar = np.array([15, 20, 35, 40, 50, 60, 75, 80, 90, 95]) 
# Qeyd: Rahat görəsiniz deyə mən rəqəmləri kiçikdən-böyüyə düzdüm.
# Real həyatda datalar qarışıq gəlir, numpy özü onları arxada düzür.

# Sual: Tələbələrin 80%-i neçə baldan AŞAĞI yığıb? (80-ci percentile)
limit = np.percentile(ballar, 80)

print(f"80-ci percentile: {limit}")

80-ci percentile: 82.0


In [45]:
# quantile() percentile ilə eynidir, sadəcə arqumenti $0$ və $1$ arasında veririk (məsələn, $50\%$ yerinə $0.5$).

maaslar = np.array([400, 500, 600, 1500, 2000, 3000, 8000])

# 0.25 (25-ci faiz, Q1)
q1 = np.quantile(maaslar, 0.25)

print(f"Ən az maaş alan 25% işçinin maaşı {q1} manatdan aşağıdır.")

Ən az maaş alan 25% işçinin maaşı 550.0 manatdan aşağıdır.


In [46]:
# np.cumsum() (Kumulyativ Cəm - Artan Yekun)

# Yanvar ayının ilk 5 günü üzrə gündəlik satış (manat)
gunluk_satis = np.array([100, 200, 150, 300, 100])

artan_yekun = np.cumsum(gunluk_satis)

print(f"Günlər üzrə cəmi qazanc: {artan_yekun}")
# Nəticə: [100, 300, 450, 750, 850]
# 2-ci gün: 100+200=300
# 3-cü gün: 300+150=450 və s.

Günlər üzrə cəmi qazanc: [100 300 450 750 850]


In [47]:
# np.where(condition, x, y) — "Ya belə, ya elə" 

"""
Excel qarşılığı: =IF(Məntiq, DoğruDəyər, YanlışDəyər)Nədir: Bu funksiya verilən şərti yoxlayır. 
Şərt ödənilirsə birinci dəyəri ($x$), ödənilmirsə ikinci dəyəri ($y$) qaytarır.
Nə üçün istifadə olunur: 
Datanı iki qrupa bölmək, etiketləmək (Labeling) və ya binar (0/1) qərarlar vermək üçün.
"""   

# İşçilərin satış rəqəmləri
satislar = np.array([12000, 8000, 15000, 5000, 10500])

# Şərt: Satış > 10000 olarsa 'Bonus', əks halda 'Standart'
status = np.where(satislar > 10000, 'Bonus', 'Standart')

print(status)
# Nəticə: ['Bonus' 'Standart' 'Bonus' 'Standart' 'Bonus']


['Bonus' 'Standart' 'Bonus' 'Standart' 'Bonus']


In [48]:
# np.select(conditions, choices) — "Çox seçimli qərar"
# Excel qarşılığı: =IFS(...) (və ya iç-içə IF funksiyaları)

"""
Nədir: np.where-in daha güclü versiyasıdır. Birdən çox şərtiniz və hər şərtə uyğun fərqli nəticəniz varsa istifadə olunur.

Nə üçün istifadə olunur: Datanı kateqoriyalara bölmək (Məsələn: Aşağı, Orta, Yüksək).
"""   

xerclemes = np.array([600, 150, 300, 50, 1000])

# Şərtlər siyahısı (Ardıcıllıq önəmlidir!)
sertler = [
    xerclemes > 500,       # 1-ci şərt (Gold)
    xerclemes > 200        # 2-ci şərt (Silver)
]

# Seçimlər siyahısı (Şərtlərə uyğun)
secimler = ['Gold', 'Silver']

# Default: Heç bir şərt ödənməzsə nə olsun? (Bronze)
kateqoriyalar = np.select(sertler, secimler, default='Bronze')

print(kateqoriyalar)
# Nəticə: ['Gold' 'Bronze' 'Silver' 'Bronze' 'Gold']

['Gold' 'Bronze' 'Silver' 'Bronze' 'Gold']


In [49]:
# np.clip(a, min, max) — "Kəsib düzəltmək (Limitləmək)" 

"""
Nədir: Datanı müəyyən bir çərçivəyə (aralığa) məcbur edir.

Minimumdan kiçik dəyərləri -> Minimuma bərabər edir.

Maksimumdan böyük dəyərləri -> Maksimuma bərabər edir.

Aralıqdakı dəyərlərə -> Toxunmur.
"""  

"""
Real Nümunə: Sorğu Anketində Yaş Xətalarının Düzəldilməsi Bir anket keçirmisiniz, amma bəzi istifadəçilər yaşlarını səhv yazıb 
(məsələn, kimsə "-5" yazıb, kimsə "200" yazıb). Siz isə analizi pozmamaq üçün yaşları 18 ilə 80 arasına sıxışdırmaq istəyirsiniz.
""" 

# İstifadəçilərin daxil etdiyi yaşlar (Səhvlərlə birlikdə)
yaslar = np.array([25, -5, 40, 150, 18, 90])

# 18-dən kiçikləri 18, 80-dən böyükləri 80 et
duzgun_yaslar = np.clip(yaslar, 18, 80)

print(f"Orijinal: {yaslar}")
print(f"Clipped : {duzgun_yaslar}")

# Nəticə:
# Orijinal: [ 25  -5  40 150  18  90]
# Clipped : [ 25  18  40  80  18  80] 
# (-5 -> 18 oldu, 150 -> 80 oldu)

Orijinal: [ 25  -5  40 150  18  90]
Clipped : [25 18 40 80 18 80]


In [50]:
# np.isnan() — "Diaqnostika"
# Məqsəd: Datanın hansı hissələrinin "xəstə" (boş) olduğunu tapır.
# Nəticə: True (boşdur) və ya False (doludur) qaytarır.

# Anbardakı qutuların sayı (NaN - məlumat yoxdur deməkdir)
qutular = np.array([50, 100, np.nan, 20, np.nan, 80])

# Hansı dəyərlər boşdur?
bosluqlar = np.isnan(qutular)

print(f"Boşluq maskası: {bosluqlar}")
# Nəticə: [False, False, True, False, True, False]

# Neçə dənə boşluq var? (True = 1 olduğu üçün cəmləyə bilərik)
bos_sayi = np.sum(bosluqlar)
print(f"Sistemdə {bos_sayi} məhsulun məlumatı yoxdur.")

Boşluq maskası: [False False  True False  True False]
Sistemdə 2 məhsulun məlumatı yoxdur.


In [51]:
"""
np.nan_to_num() — "Təmir və Yamaq"
Məqsəd: NaN dəyərlərini riyazi əməliyyat apara bilmək üçün real bir ədədə çevirir.

Varsayılan: Heç nə qeyd etməsəniz, NaN-ı 0-a çevirir.

Real İstifadə: Maşın öyrənməsi (Machine Learning) modelləri NaN qəbul etmir. Modeli işə salmaq üçün boşluqları doldurmalısınız (məsələn, 0 ilə).
"""  

# Boşluqları 0 ilə əvəz et (Sanki 'yoxdur' kimi qəbul edirik)
temiz_qutular = np.nan_to_num(qutular, nan=0)

print(f"Orijinal: {qutular}")
print(f"Təmiz   : {temiz_qutular}")

# Nəticə:
# Orijinal: [ 50. 100. nan  20. nan  80.]
# Təmiz   : [ 50. 100.   0.  20.   0.  80.]

Orijinal: [ 50. 100.  nan  20.  nan  80.]
Təmiz   : [ 50. 100.   0.  20.   0.  80.]


In [53]:
# np.nanmean() və np.nanmedian() — "Ağıllı Hesablama" 
# Problem: Adi np.mean() funksiyası massivdə bir dənə belə NaN görsə, nəticəni NaN çıxarır. Çünki riyaziyyatda "bilinməyən"lə toplama edə bilməzsiniz.
# Həll: np.nanmean() funksiyası boşluqları görməzdən gəlir (sanki onlar yoxdur) və qalan ədədlərin ortalamasını tapır.

gelirler = np.array([1000, 2000, np.nan, 3000])

# Səhv yanaşma
sehv_orta = np.mean(gelirler)
print(f"Adi Mean: {sehv_orta}") 
# Nəticə: nan (Hesablaya bilmədi)

# Doğru yanaşma
dogru_orta = np.nanmean(gelirler)
print(f"NanMean : {dogru_orta:.2f}") 
# Nəticə: 2000.0 ( (1000+2000+3000)/3 )

Adi Mean: nan
NanMean : 2000.00


In [55]:
gelirler = np.array([1000, 2000, np.nan, 3000])

# Səhv yanaşma
sehv_orta = np.median(gelirler)
print(f"Adi Mean: {sehv_orta}") 
# Nəticə: nan (Hesablaya bilmədi)

# Doğru yanaşma
dogru_orta = np.nanmedian(gelirler)
print(f"NanMean : {dogru_orta:.2f}") 
# Nəticə: 2000.0 ( (1000+2000+3000)/3 )

Adi Mean: nan
NanMean : 2000.00


In [61]:
"""
np.concatenate((a, b), axis=...) — Universal Yapışdırıcı
Bu funksiya ən ümumi birləşdirmə vasitəsidir. Həm alt-alta, həm yan-yana birləşdirə bilir, sadəcə axis (ox) parametrini dəyişmək lazımdır.

axis=0: Alt-alta (Sətir kimi) - Defolt budur

axis=1: Yan-yana (Sütun kimi)
"""  

import numpy as np

rub_1 = np.array([10, 20, 30])
rub_2 = np.array([40, 50, 60])

# İllik ümumi siyahı yaratmaq (Ucu-uca əlavə edir)
illik = np.concatenate((rub_1, rub_2))

print(illik)
# Nəticə: [10 20 30 40 50 60]

[10 20 30 40 50 60]


In [65]:
# np.vstack() — Vertical Stack (Alt-alta yığmaq)

# Filial A-nın işçiləri (Ad, Yaş)
filial_A = np.array([
    ["Ali", "25"],
    ["Vali", "30"]
])


# Filial B-nin işçiləri
filial_B = np.array([
    ["Samir", "22"],
    ["Nigar", "28"]
])

# Alt-alta birləşdir (Sətir artır)
umum_baza = np.vstack((filial_A, filial_B))

print(umum_baza)
# Nəticə:
# [['Ali'   '25']
#  ['Vali'  '30']
#  ['Samir' '22']
#  ['Nigar' '28']]

[['Ali' '25']
 ['Vali' '30']
 ['Samir' '22']
 ['Nigar' '28']]


In [66]:
# np.hstack() — Horizontal Stack (Yan-yana qoymaq) 

# Sütun 1: Adlar (Şaquli forma üçün reshape edirik)
adlar = np.array(["Ali", "Vali", "Samir"]).reshape(-1, 1)

# Sütun 2: Maaşlar
maaslar = np.array([1000, 1500, 1200]).reshape(-1, 1)

# Yan-yana birləşdir (Sütun artır)
cedvel = np.hstack((adlar, maaslar))

print(cedvel)
# Nəticə:
# [['Ali'   '1000']
#  ['Vali'  '1500']
#  ['Samir' '1200']]

[['Ali' '1000']
 ['Vali' '1500']
 ['Samir' '1200']]


In [77]:
a = np.array([1,2,3,4,"Vahid","Jet","salam","data"])
print(a)

a.reshape(2,4)

['1' '2' '3' '4' 'Vahid' 'Jet' 'salam' 'data']


array([['1', '2', '3', '4'],
       ['Vahid', 'Jet', 'salam', 'data']], dtype='<U21')

In [89]:

# 1. Qarışıq səbət (Məlumat)
satislar = np.array(['Notebook', 'Maus', 'Notebook', 'Klaviatura', 'Maus', 'Notebook'])

# 2. Funksiyanı çağırırıq
# mehsullar -> Təkrarsız adlar siyahısı olacaq
# saylar    -> Uyğun saylar siyahısı olacaq
mehsullar, saylar = np.unique(satislar, return_counts=True)

print(mehsullar)
print(saylar,end="\n\n")

c = np.column_stack((mehsullar,saylar))
print(c)

['Klaviatura' 'Maus' 'Notebook']
[1 2 3]

[['Klaviatura' '1']
 ['Maus' '2']
 ['Notebook' '3']]


In [90]:
# np.intersect1d: Kəsişmə (Hər iki siyahıda olanlar). 
# np.setdiff1d: Fərq (Birində olub, digərində olmayanlar).
# np.union1d: Birləşmə (Təkrarsız ümumi siyahı).

yanvar_musterileri = np.array(['Ali', 'Vali', 'Hasan', 'Nigar'])
fevral_musterileri = np.array(['Ali', 'Nigar', 'Samir'])

# 1. Sadiq müştərilər (Hər iki ayda olanlar)
sadiq = np.intersect1d(yanvar_musterileri, fevral_musterileri)
print(f"Sadiq müştərilər: {sadiq}") 
# Nəticə: ['Ali' 'Nigar']

# 2. İtirilmiş müştərilər (Yanvarda var, Fevralda yoxdur)
itirilen = np.setdiff1d(yanvar_musterileri, fevral_musterileri)
print(f"Bizi tərk edənlər: {itirilen}") 
# Nəticə: ['Hasan' 'Vali']

# 3. Yeni gələnlər (Fevralda var, Yanvarda yoxdur)
yeni = np.setdiff1d(fevral_musterileri, yanvar_musterileri)
print(f"Yeni qoşulanlar: {yeni}") 
# Nəticə: ['Samir']

Sadiq müştərilər: ['Ali' 'Nigar']
Bizi tərk edənlər: ['Hasan' 'Vali']
Yeni qoşulanlar: ['Samir']


In [96]:

# --- Məlumat Bazası ---

# Satılan Məhsullar (Kateqoriyalar)
mehsullar = np.array(['Noutbuk', 'Maus', 'Telefon', 'Noutbuk', 'Maus', 'Monitor', 'Telefon', 'Noutbuk'])

# Qiymətlər (Bəzi qiymətlər sistemdən silinib - NaN)
qiymetler = np.array([1500, 30, 800, np.nan, 30, 400, 800, 1600])

# Satış Miqdarı (Dəyərlərdən biri səhvən mənfi yazılıb - Təmizlənməlidir)
miqdar = np.array([2, 10, 5, 1, 15, 3, 4, -5]) 

# Yanvar ayı Müştəri ID-ləri
yanvar_musteri = np.array([101, 102, 103, 104, 105])

# Fevral ayı Müştəri ID-ləri
fevral_musteri = np.array([103, 104, 106, 107])


print("--- 1. Məlumat Təmizliyi ---")

# A. Qiymətlərdəki boşluqları (NaN) orta qiymətlə dolduraq
# Əvvəl orta qiyməti tapaq (boşluqları görməzdən gələrək)
orta_qiymet = np.nanmean(qiymetler) 
# Boş yerlərə bu ortanı yazaq
qiymetler_temiz = np.nan_to_num(qiymetler, nan=orta_qiymet)

print(f"Düzəlmiş Qiymətlər: {qiymetler_temiz}")

# B. Miqdardakı mənfi ədədləri düzəldək (Mənfiləri 0 edək - Clip)
# Min: 0, Max: Sonsuzluq (np.inf) və ya böyük bir rəqəm
miqdar_temiz = np.clip(miqdar, 0, 1000)

print(f"Düzəlmiş Miqdar: {miqdar_temiz}")


print("\n--- 2. Maliyyə Hesabatı ---")

# Element-element vurma (Vectorization)
gelir = qiymetler_temiz * miqdar_temiz

print(f"Hər satışdan gəlir: {gelir}")

# Ümumi Gəlir (Sum)
total_gelir = np.sum(gelir)
print(f"Mağazanın Toplam Gəliri: {total_gelir:.2f} AZN")

# Ən bahalı satış (Max)
max_gelir = np.max(gelir)
print(f"Tək seferdə ən böyük satış: {max_gelir:.2f} AZN")

print("\n--- 3. Məhsul Analizi ---")

unikal_mehsullar, saylar = np.unique(mehsullar, return_counts=True)

# Səliqəli cədvəl üçün column_stack
cedvel = np.column_stack((unikal_mehsullar, saylar))

print("Satış sayı üzrə hesabat:")
print(cedvel)

print("\n--- 4. Müştəri Hərəkəti (CRM) ---")

# Sadiq Müştərilər (Hər iki ayda olanlar - Intersect)
sadiq = np.intersect1d(yanvar_musteri, fevral_musteri)
print(f"Qayıdan (Sadiq) Müştərilər: {sadiq}")

# İtirilmiş Müştərilər (Yanvarda var, Fevralda yox - SetDiff A-B)
itirilen = np.setdiff1d(yanvar_musteri, fevral_musteri)
print(f"İtirilmiş Müştərilər: {itirilen}")

# Yeni Müştərilər (Fevralda var, Yanvarda yox - SetDiff B-A)
yeni = np.setdiff1d(fevral_musteri, yanvar_musteri)
print(f"Yeni Qazanılan Müştərilər: {yeni}")

print("\n--- 5. VIP Satışlar ---")

# Şərt (Maska) yaradırıq
vip_maska = gelir > 2000

# Maskani tətbiq edirik
vip_mehsullar = mehsullar[vip_maska]
vip_gelirler = gelir[vip_maska]

# Nəticəni birləşdirib göstərək
vip_cedvel = np.column_stack((vip_mehsullar, vip_gelirler))
print(vip_cedvel)



--- 1. Məlumat Təmizliyi ---
Düzəlmiş Qiymətlər: [1500.           30.          800.          737.14285714   30.
  400.          800.         1600.        ]
Düzəlmiş Miqdar: [ 2 10  5  1 15  3  4  0]

--- 2. Maliyyə Hesabatı ---
Hər satışdan gəlir: [3000.          300.         4000.          737.14285714  450.
 1200.         3200.            0.        ]
Mağazanın Toplam Gəliri: 12887.14 AZN
Tək seferdə ən böyük satış: 4000.00 AZN

--- 3. Məhsul Analizi ---
Satış sayı üzrə hesabat:
[['Maus' '2']
 ['Monitor' '1']
 ['Noutbuk' '3']
 ['Telefon' '2']]

--- 4. Müştəri Hərəkəti (CRM) ---
Qayıdan (Sadiq) Müştərilər: [103 104]
İtirilmiş Müştərilər: [101 102 105]
Yeni Qazanılan Müştərilər: [106 107]

--- 5. VIP Satışlar ---
[['Noutbuk' '3000.0']
 ['Telefon' '4000.0']
 ['Telefon' '3200.0']]


In [97]:
# Futbol Matçı Analizi (Sports Analytics) 
# 1. məsafədə olan nan dəyərləri ortalama ilə əvəz edirsiniz (nanmean,nan_to_num)
# 2. pas deqiqiliyi 0 ve 100 faiz arasinda ola biler uygun olmuyan deyerleri evez edersiniz(clip)
# 3. en çox qaçış məsafəsi hansı oyunçudadır ? argmax
# Faydalılıq Xalı = (Qol * 5) + Qaçış Məsafəsi 
# 20-dən yuxarı xal toplayanları tapaq (Maska yaradaq) 
# Komandanı tərk edənlər (Keçən ildə olub, Bu ildə olmayanlar) np.setdiff1d
# Yeni gelenler np.setdiff1d

# --- 0. Verilənlər (Xam Data) ---
oyuncular = np.array(['Ronaldo', 'Messi', 'Mbappe', 'Salah', 'Neymar', 'Haaland', 'Lewandowski'])
qollar = np.array([2, 0, 3, 1, 0, 4, 0])
mesafe = np.array([10.5, 9.8, np.nan, 11.2, np.nan, 9.5, 10.0])
pas_deqiqliyi = np.array([85, 92, 400, 78, 150, 88, 90])

kecen_il = np.array([10, 7, 11, 9, 20])
bu_il = np.array([10, 11, 9, 22, 30])


print("--- 1. Məlumat Təmizliyi (Data Cleaning) ---")

# A. Məsafədəki boşluqları ortalama ilə dolduraq
# nanmean boşluqları nəzərə almadan ortalamanı tapır
orta_mesafe = np.nanmean(mesafe) 
# nan_to_num boşluqların yerinə bu ortalamanı yazır
mesafe_temiz = np.nan_to_num(mesafe, nan=orta_mesafe)

print(f"Düzəlmiş Məsafələr: {mesafe_temiz}")

# B. Pas dəqiqliyini düzəltmək (Maksimum 100 ola bilər)
pas_temiz = np.clip(pas_deqiqliyi, 0, 100)

print(f"Düzəlmiş Pas Dəqiqliyi: {pas_temiz}")


print("\n--- 2. Performans Analizi (Statistics) ---")

# Cəmi qol sayı
cem_qol = np.sum(qollar)
print(f"Komandanın cəmi qolu: {cem_qol}")

# Ən çox qaçan oyunçu kimdir?
# addım 1: Ən çox qaçış məsafəsi hansı indeksdədir? (argmax indeksi verir)
en_suretli_indeks = np.argmax(mesafe_temiz) 
# addım 2: Həmin indeksi oyunçular massivinə veririk
en_suretli_oyuncu = oyuncular[en_suretli_indeks]

print(f"Ən çox qaçan: {en_suretli_oyuncu}")


print("\n--- 3. MVP Seçimi (Calculation & Filter) ---")

# Faydalılıq Xalı = (Qol * 5) + Qaçış Məsafəsi
xallar = (qollar * 5) + mesafe_temiz

# 20-dən yuxarı xal toplayanları tapaq (Maska yaradaq)
mvp_maska = xallar > 20

# Maskani tətbiq edib adları və xalları seçək
mvp_adlar = oyuncular[mvp_maska]
mvp_xallar = xallar[mvp_maska]

# Nəticəni cədvəl kimi birləşdirək
mvp_cedvel = np.column_stack((mvp_adlar, mvp_xallar))

print("MVP Oyunçular (Ad | Xal):")
print(mvp_cedvel)


print("\n--- 4. Transfer Analizi (Set Operations) ---")

# Komandanı tərk edənlər (Keçən ildə olub, Bu ildə olmayanlar)
gedenler = np.setdiff1d(kecen_il, bu_il)
print(f"Gedənlərin ID-ləri: {gedenler}")

# Yeni gələnlər (Bu ildə olub, Keçən ildə olmayanlar)
gelenler = np.setdiff1d(bu_il, kecen_il)
print(f"Yenilərin ID-ləri: {gelenler}")

--- 1. Məlumat Təmizliyi (Data Cleaning) ---
Düzəlmiş Məsafələr: [10.5  9.8 10.2 11.2 10.2  9.5 10. ]
Düzəlmiş Pas Dəqiqliyi: [ 85  92 100  78 100  88  90]

--- 2. Performans Analizi (Statistics) ---
Komandanın cəmi qolu: 10
Ən çox qaçan: Salah

--- 3. MVP Seçimi (Calculation & Filter) ---
MVP Oyunçular (Ad | Xal):
[['Ronaldo' '20.5']
 ['Mbappe' '25.2']
 ['Haaland' '29.5']]

--- 4. Transfer Analizi (Set Operations) ---
Gedənlərin ID-ləri: [ 7 20]
Yenilərin ID-ləri: [22 30]
